// <auto-generated />
using System;
using System.Collections.Generic;
using DbContextExtensionsExamples;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbContextExtensionsExamples.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20260309044834_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.ComplexOwnedTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ComplexShippingAddress", "DbContextExtensionsExamples.Entities.ComplexOwnedTypeOrder.ComplexShippingAddress#ComplexTypeAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DbContextExtensionsExamples.Entities.ComplexOwnedTypeOrder.ComplexShippingAddress#ComplexTypeAddress.Location#ComplexTypeLocation", b2 =>
                                {
                                    b2.Property<double>("Lat")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Lng")
                                        .HasColumnType("double precision");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("ComplexOwnedTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.ComplexTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ShippingAddress", "DbContextExtensionsExamples.Entities.ComplexTypeOrder.ShippingAddress#ComplexTypeAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DbContextExtensionsExamples.Entities.ComplexTypeOrder.ShippingAddress#ComplexTypeAddress.Location#ComplexTypeLocation", b2 =>
                                {
                                    b2.Property<double>("Lat")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Lng")
                                        .HasColumnType("double precision");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("ComplexTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.CompositeKeyRow", b =>
                {
                    b.Property<int>("Id1")
                        .HasColumnType("integer");

                    b.Property<int>("Id2")
                        .HasColumnType("integer");

                    b.Property<int>("Column1")
                        .HasColumnType("integer");

                    b.Property<string>("Column2")
                        .HasColumnType("text");

                    b.Property<DateTime>("Column3")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id1", "Id2");

                    b.ToTable("CompositeKeyRows");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.ConfigurationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id1")
                        .HasDefaultValueSql("uuid_generate_v1mc()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("Key1");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int?>("SeasonAsInt")
                        .HasColumnType("integer");

                    b.Property<string>("SeasonAsString")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationEntries");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.JsonComplexOwnedTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ComplexShippingAddress", "DbContextExtensionsExamples.Entities.JsonComplexOwnedTypeOrder.ComplexShippingAddress#ComplexTypeAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Street");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DbContextExtensionsExamples.Entities.JsonComplexOwnedTypeOrder.ComplexShippingAddress#ComplexTypeAddress.Location#ComplexTypeLocation", b2 =>
                                {
                                    b2.Property<double>("Lat");

                                    b2.Property<double>("Lng");

                                    b2.HasJsonPropertyName("xxx");
                                });

                            b1.ToJson("ComplexShippingAddress");
                        });

                    b.HasKey("Id");

                    b.ToTable("JsonComplexOwnedTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.JsonComplexTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ShippingAddress", "DbContextExtensionsExamples.Entities.JsonComplexTypeOrder.ShippingAddress#ComplexTypeAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Street");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DbContextExtensionsExamples.Entities.JsonComplexTypeOrder.ShippingAddress#ComplexTypeAddress.Location#ComplexTypeLocation", b2 =>
                                {
                                    b2.Property<double>("Lat");

                                    b2.Property<double>("Lng");

                                    b2.HasJsonPropertyName("xxx");
                                });

                            b1.ToJson("ShippingAddress");
                        });

                    b.HasKey("Id");

                    b.ToTable("JsonComplexTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.JsonOwnedTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("JsonOwnedTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.OwnedTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("OwnedTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Column1")
                        .HasColumnType("integer");

                    b.Property<string>("Column2")
                        .HasColumnType("text");

                    b.Property<DateTime>("Column3")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.ComplexOwnedTypeOrder", b =>
                {
                    b.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeAddress", "OwnedShippingAddress", b1 =>
                        {
                            b1.Property<int>("ComplexOwnedTypeOrderId")
                                .HasColumnType("integer");

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.HasKey("ComplexOwnedTypeOrderId");

                            b1.ToTable("ComplexOwnedTypeOrders");

                            b1.WithOwner()
                                .HasForeignKey("ComplexOwnedTypeOrderId");

                            b1.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeLocation", "Location", b2 =>
                                {
                                    b2.Property<int>("OwnedTypeAddressComplexOwnedTypeOrderId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Lat")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Lng")
                                        .HasColumnType("double precision");

                                    b2.HasKey("OwnedTypeAddressComplexOwnedTypeOrderId");

                                    b2.ToTable("ComplexOwnedTypeOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedTypeAddressComplexOwnedTypeOrderId");
                                });

                            b1.Navigation("Location");
                        });

                    b.Navigation("OwnedShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.JsonComplexOwnedTypeOrder", b =>
                {
                    b.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeAddress", "OwnedShippingAddress", b1 =>
                        {
                            b1.Property<int>("JsonComplexOwnedTypeOrderId");

                            b1.Property<string>("Street");

                            b1.HasKey("JsonComplexOwnedTypeOrderId");

                            b1.ToTable("JsonComplexOwnedTypeOrders");

                            b1.ToJson("OwnedShippingAddress");

                            b1.WithOwner()
                                .HasForeignKey("JsonComplexOwnedTypeOrderId");

                            b1.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeLocation", "Location", b2 =>
                                {
                                    b2.Property<int>("OwnedTypeAddressJsonComplexOwnedTypeOrderId");

                                    b2.Property<double>("Lat");

                                    b2.Property<double>("Lng");

                                    b2.HasKey("OwnedTypeAddressJsonComplexOwnedTypeOrderId");

                                    b2.ToTable("JsonComplexOwnedTypeOrders");

                                    b2.HasJsonPropertyName("xxx");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedTypeAddressJsonComplexOwnedTypeOrderId");
                                });

                            b1.Navigation("Location");
                        });

                    b.Navigation("OwnedShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.JsonOwnedTypeOrder", b =>
                {
                    b.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("JsonOwnedTypeOrderId");

                            b1.Property<string>("Street");

                            b1.HasKey("JsonOwnedTypeOrderId");

                            b1.ToTable("JsonOwnedTypeOrders");

                            b1.ToJson("ShippingAddress");

                            b1.WithOwner()
                                .HasForeignKey("JsonOwnedTypeOrderId");

                            b1.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeLocation", "Location", b2 =>
                                {
                                    b2.Property<int>("OwnedTypeAddressJsonOwnedTypeOrderId");

                                    b2.Property<double>("Lat");

                                    b2.Property<double>("Lng");

                                    b2.HasKey("OwnedTypeAddressJsonOwnedTypeOrderId");

                                    b2.ToTable("JsonOwnedTypeOrders");

                                    b2.HasJsonPropertyName("xxx");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedTypeAddressJsonOwnedTypeOrderId");
                                });

                            b1.Navigation("Location");
                        });

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.OwnedTypeOrder", b =>
                {
                    b.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("OwnedTypeOrderId")
                                .HasColumnType("integer");

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.HasKey("OwnedTypeOrderId");

                            b1.ToTable("OwnedTypeOrders");

                            b1.WithOwner()
                                .HasForeignKey("OwnedTypeOrderId");

                            b1.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeLocation", "Location", b2 =>
                                {
                                    b2.Property<int>("OwnedTypeAddressOwnedTypeOrderId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Lat")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Lng")
                                        .HasColumnType("double precision");

                                    b2.HasKey("OwnedTypeAddressOwnedTypeOrderId");

                                    b2.ToTable("OwnedTypeOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedTypeAddressOwnedTypeOrderId");
                                });

                            b1.Navigation("Location");
                        });

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
