namespace EntityFrameworkCore.PostgreSQL.SimpleBulks
{
    public static class Constants
    {
        public const string AutoGeneratedIndexNumberColumn = "AutoGeneratedIndexNumberColumn";
        public const string DefaultCollation = "";
    }
}
