namespace EntityFrameworkCore.PostgreSQL.SimpleBulks;

public static class Constants
{
    public const string AutoGeneratedIndexNumberColumn = "AutoGeneratedIndexNumberColumn";
    public const string DefaultCollation = "";
    public const string BeginQuote = "\"";
    public const string EndQuote = "\"";
}
