using EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkDelete;
using EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkInsert;
using EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkMatch;
using EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkMerge;
using EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkUpdate;
using EntityFrameworkCore.PostgreSQL.SimpleBulks.TempTable;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace EntityFrameworkCore.PostgreSQL.SimpleBulks.Extensions;

public static class ConnectionContextExtensions
{
    private static readonly BulkOptions DefaultBulkOptions = new BulkOptions()
    {
        BatchSize = 0,
        Timeout = 30,
    };

    public static void EnsureOpen(this ConnectionContext connection)
    {
        var connectionState = connection.Connection.State;

        if (connectionState != ConnectionState.Open)
        {
            connection.Connection.Open();
        }
    }

    public static async Task EnsureOpenAsync(this ConnectionContext connection, CancellationToken cancellationToken = default)
    {
        var connectionState = connection.Connection.State;

        if (connectionState != ConnectionState.Open)
        {
            await connection.Connection.OpenAsync(cancellationToken);
        }
    }

    public static void EnsureClosed(this ConnectionContext connection)
    {
        var connectionState = connection.Connection.State;

        if (connectionState != ConnectionState.Closed)
        {
            connection.Connection.Close();
        }
    }

    public static NpgsqlCommand CreateTextCommand(this ConnectionContext connection, string commandText, BulkOptions options = null)
    {
        options ??= DefaultBulkOptions;

        var command = connection.Connection.CreateCommand();
        command.Transaction = connection.Transaction;
        command.CommandText = commandText;
        command.CommandTimeout = options.Timeout;
        return command;
    }

    public static void SqlBulkCopy<T>(this ConnectionContext connectionContext, IEnumerable<T> data, string tableName, IEnumerable<string> propertyNames, IReadOnlyDictionary<string, string> columnNameMappings, bool addIndexNumberColumn, BulkOptions options = null, IReadOnlyDictionary<string, ValueConverter> valueConverters = null)
    {
        options ??= DefaultBulkOptions;

        var properties = TypeDescriptor.GetProperties(typeof(T));

        var updatablePros = new List<PropertyDescriptor>();
        foreach (PropertyDescriptor prop in properties)
        {
            if (propertyNames.Contains(prop.Name))
            {
                updatablePros.Add(prop);
            }
        }

        var columnNamesToInsert = propertyNames.ToList();

        if (addIndexNumberColumn)
        {
            columnNamesToInsert.Add(Constants.AutoGeneratedIndexNumberColumn);
        }

        var sql = $"COPY {tableName} ({string.Join(',', columnNamesToInsert.Select(x => $"\"{GetDbColumnName(x, columnNameMappings)}\""))}) FROM STDIN (FORMAT binary)";

        using var writer = connectionContext.Connection.BeginBinaryImport(sql);

        long idx = 0;

        foreach (T item in data)
        {
            writer.StartRow();

            foreach (var name in columnNamesToInsert)
            {
                var prop = updatablePros.FirstOrDefault(x => x.Name == name);

                if (prop == null)
                {
                    continue;
                }

                var value = GetProviderValue(prop, item, valueConverters);

                writer.Write(value);
            }

            if (addIndexNumberColumn)
            {
                writer.Write(idx);
            }

            idx++;
        }

        writer.Complete();
    }

    public static async Task SqlBulkCopyAsync<T>(this ConnectionContext connectionContext, IEnumerable<T> data, string tableName, IEnumerable<string> propertyNames, IReadOnlyDictionary<string, string> columnNameMappings, bool addIndexNumberColumn, BulkOptions options = null, IReadOnlyDictionary<string, ValueConverter> valueConverters = null, CancellationToken cancellationToken = default)
    {
        options ??= DefaultBulkOptions;

        var properties = TypeDescriptor.GetProperties(typeof(T));

        var updatablePros = new List<PropertyDescriptor>();
        foreach (PropertyDescriptor prop in properties)
        {
            if (propertyNames.Contains(prop.Name))
            {
                updatablePros.Add(prop);
            }
        }

        var columnNamesToInsert = propertyNames.ToList();

        if (addIndexNumberColumn)
        {
            columnNamesToInsert.Add(Constants.AutoGeneratedIndexNumberColumn);
        }

        var sql = $"COPY {tableName} ({string.Join(',', columnNamesToInsert.Select(x => $"\"{GetDbColumnName(x, columnNameMappings)}\""))}) FROM STDIN (FORMAT binary)";

        using var writer = await connectionContext.Connection.BeginBinaryImportAsync(sql, cancellationToken);

        long idx = 0;

        foreach (T item in data)
        {
            cancellationToken.ThrowIfCancellationRequested();

            await writer.StartRowAsync(cancellationToken);

            foreach (var name in columnNamesToInsert)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var prop = updatablePros.FirstOrDefault(x => x.Name == name);

                if (prop == null)
                {
                    continue;
                }

                var value = GetProviderValue(prop, item, valueConverters);

                await writer.WriteAsync(value, cancellationToken);
            }

            if (addIndexNumberColumn)
            {
                await writer.WriteAsync(idx, cancellationToken);
            }

            idx++;
        }

        await writer.CompleteAsync(cancellationToken);
    }

    private static string GetDbColumnName(string columName, IReadOnlyDictionary<string, string> columnNameMappings)
    {
        if (columnNameMappings == null)
        {
            return columName;
        }

        return columnNameMappings.TryGetValue(columName, out string value) ? value : columName;
    }

    private static object GetProviderValue<T>(PropertyDescriptor property, T item, IReadOnlyDictionary<string, ValueConverter> valueConverters)
    {
        if (valueConverters != null && valueConverters.TryGetValue(property.Name, out var converter))
        {
            return converter.ConvertToProvider(property.GetValue(item));
        }

        var type = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;
        var tempValue = property.GetValue(item);
        var value = type.IsEnum && tempValue != null ? (int)tempValue : tempValue;

        return value;
    }

    public static BulkInsertBuilder<T> CreateBulkInsertBuilder<T>(this ConnectionContext connectionContext)
    {
        return new BulkInsertBuilder<T>(connectionContext);
    }

    public static BulkUpdateBuilder<T> CreateBulkUpdateBuilder<T>(this ConnectionContext connectionContext)
    {
        return new BulkUpdateBuilder<T>(connectionContext);
    }

    public static BulkDeleteBuilder<T> CreateBulkDeleteBuilder<T>(this ConnectionContext connectionContext)
    {
        return new BulkDeleteBuilder<T>(connectionContext);
    }

    public static BulkMergeBuilder<T> CreateBulkMergeBuilder<T>(this ConnectionContext connectionContext)
    {
        return new BulkMergeBuilder<T>(connectionContext);
    }

    public static BulkMatchBuilder<T> CreateBulkMatchBuilder<T>(this ConnectionContext connectionContext)
    {
        return new BulkMatchBuilder<T>(connectionContext);
    }

    public static TempTableBuilder<T> CreateTempTableBuilder<T>(this ConnectionContext connectionContext)
    {
        return new TempTableBuilder<T>(connectionContext);
    }
}
