using EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkDelete;
using EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkInsert;
using EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkMatch;
using EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkMerge;
using EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkUpdate;
using EntityFrameworkCore.PostgreSQL.SimpleBulks.TempTable;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace EntityFrameworkCore.PostgreSQL.SimpleBulks.Extensions;

public static class ConnectionContextExtensions
{
    private static readonly BulkOptions DefaultBulkOptions = new BulkOptions()
    {
        BatchSize = 0,
        Timeout = 30,
    };

    public static void EnsureOpen(this ConnectionContext connection)
    {
        var connectionState = connection.Connection.State;

        if (connectionState != ConnectionState.Open)
        {
            connection.Connection.Open();
        }
    }

    public static async Task EnsureOpenAsync(this ConnectionContext connection, CancellationToken cancellationToken = default)
    {
        var connectionState = connection.Connection.State;

        if (connectionState != ConnectionState.Open)
        {
            await connection.Connection.OpenAsync(cancellationToken);
        }
    }

    public static void EnsureClosed(this ConnectionContext connection)
    {
        var connectionState = connection.Connection.State;

        if (connectionState != ConnectionState.Closed)
        {
            connection.Connection.Close();
        }
    }

    public static NpgsqlCommand CreateTextCommand(this ConnectionContext connection, string commandText, BulkOptions options = null)
    {
        options ??= DefaultBulkOptions;

        var command = connection.Connection.CreateCommand();
        command.Transaction = connection.Transaction;
        command.CommandText = commandText;
        command.CommandTimeout = options.Timeout;
        return command;
    }

    public static void SqlBulkCopy<T>(this ConnectionContext connectionContext,
        IReadOnlyCollection<T> data, string tableName,
        IReadOnlyCollection<string> propertyNames,
        IReadOnlyDictionary<string, string> columnNameMappings,
        bool addIndexNumberColumn,
        BulkOptions options = null,
        IReadOnlyDictionary<string, ValueConverter> valueConverters = null,
        Discriminator discriminator = null)
    {
        options ??= DefaultBulkOptions;

        var columnNamesToInsert = propertyNames.ToList();

        if (addIndexNumberColumn)
        {
            columnNamesToInsert.Add(Constants.AutoGeneratedIndexNumberColumn);
        }

        var hasDiscriminator = discriminator != null && !columnNamesToInsert.Contains(discriminator.PropertyName);

        if (hasDiscriminator)
        {
            columnNamesToInsert.Add(discriminator.PropertyName);
        }

        var sql = $"COPY {tableName} ({string.Join(',', columnNamesToInsert.Select(x => $"\"{GetDbColumnName(x, columnNameMappings)}\""))}) FROM STDIN (FORMAT binary)";

        using var writer = connectionContext.Connection.BeginBinaryImport(sql);

        long idx = 0;

        foreach (T item in data)
        {
            writer.StartRow();

            foreach (var name in propertyNames)
            {
                var value = PropertiesCache<T>.GetPropertyValue(name, item, valueConverters);

                writer.Write(value);
            }

            if (addIndexNumberColumn)
            {
                writer.Write(idx);
            }

            if (hasDiscriminator)
            {
                writer.Write(discriminator.PropertyValue);
            }

            idx++;
        }

        writer.Complete();
    }

    public static async Task SqlBulkCopyAsync<T>(this ConnectionContext connectionContext,
        IReadOnlyCollection<T> data, string tableName,
        IReadOnlyCollection<string> propertyNames,
        IReadOnlyDictionary<string, string> columnNameMappings,
        bool addIndexNumberColumn,
        BulkOptions options = null,
        IReadOnlyDictionary<string, ValueConverter> valueConverters = null,
        Discriminator discriminator = null,
        CancellationToken cancellationToken = default)
    {
        options ??= DefaultBulkOptions;

        var columnNamesToInsert = propertyNames.ToList();

        if (addIndexNumberColumn)
        {
            columnNamesToInsert.Add(Constants.AutoGeneratedIndexNumberColumn);
        }

        var hasDiscriminator = discriminator != null && !columnNamesToInsert.Contains(discriminator.PropertyName);

        if (hasDiscriminator)
        {
            columnNamesToInsert.Add(discriminator.PropertyName);
        }

        var sql = $"COPY {tableName} ({string.Join(',', columnNamesToInsert.Select(x => $"\"{GetDbColumnName(x, columnNameMappings)}\""))}) FROM STDIN (FORMAT binary)";

        using var writer = await connectionContext.Connection.BeginBinaryImportAsync(sql, cancellationToken);

        long idx = 0;

        foreach (T item in data)
        {
            cancellationToken.ThrowIfCancellationRequested();

            await writer.StartRowAsync(cancellationToken);

            foreach (var name in propertyNames)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var value = PropertiesCache<T>.GetPropertyValue(name, item, valueConverters);

                await writer.WriteAsync(value, cancellationToken);
            }

            if (addIndexNumberColumn)
            {
                await writer.WriteAsync(idx, cancellationToken);
            }

            if (hasDiscriminator)
            {
                await writer.WriteAsync(discriminator.PropertyValue, cancellationToken);
            }

            idx++;
        }

        await writer.CompleteAsync(cancellationToken);
    }

    private static string GetDbColumnName(string columName, IReadOnlyDictionary<string, string> columnNameMappings)
    {
        if (columnNameMappings == null)
        {
            return columName;
        }

        return columnNameMappings.TryGetValue(columName, out string value) ? value : columName;
    }

    public static void ExecuteReader(this ConnectionContext connectionContext, string commandText, Action<IDataReader> action, BulkOptions options = null)
    {
        using var command = connectionContext.CreateTextCommand(commandText, options);
        using var reader = command.ExecuteReader();

        while (reader.Read())
        {
            action(reader);
        }
    }

    public static BulkInsertBuilder<T> CreateBulkInsertBuilder<T>(this ConnectionContext connectionContext)
    {
        return new BulkInsertBuilder<T>(connectionContext);
    }

    public static BulkUpdateBuilder<T> CreateBulkUpdateBuilder<T>(this ConnectionContext connectionContext)
    {
        return new BulkUpdateBuilder<T>(connectionContext);
    }

    public static BulkDeleteBuilder<T> CreateBulkDeleteBuilder<T>(this ConnectionContext connectionContext)
    {
        return new BulkDeleteBuilder<T>(connectionContext);
    }

    public static BulkMergeBuilder<T> CreateBulkMergeBuilder<T>(this ConnectionContext connectionContext)
    {
        return new BulkMergeBuilder<T>(connectionContext);
    }

    public static BulkMatchBuilder<T> CreateBulkMatchBuilder<T>(this ConnectionContext connectionContext)
    {
        return new BulkMatchBuilder<T>(connectionContext);
    }

    public static TempTableBuilder<T> CreateTempTableBuilder<T>(this ConnectionContext connectionContext)
    {
        return new TempTableBuilder<T>(connectionContext);
    }
}
