using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace EntityFrameworkCore.PostgreSQL.SimpleBulks.Extensions;

public static class IListExtensions
{
    private static readonly BulkOptions DefaultBulkOptions = new BulkOptions()
    {
        BatchSize = 0,
        Timeout = 30,
    };

    public static void SqlBulkCopy<T>(this IEnumerable<T> data, string tableName, IEnumerable<string> propertyNames, IReadOnlyDictionary<string, string> columnNameMappings, bool addIndexNumberColumn, ConnectionContext connectionContext, BulkOptions options = null, IReadOnlyDictionary<string, ValueConverter> valueConverters = null)
    {
        options ??= DefaultBulkOptions;

        var properties = TypeDescriptor.GetProperties(typeof(T));

        var updatablePros = new List<PropertyDescriptor>();
        foreach (PropertyDescriptor prop in properties)
        {
            if (propertyNames.Contains(prop.Name))
            {
                updatablePros.Add(prop);
            }
        }

        var columnNamesToInsert = propertyNames.ToList();

        if (addIndexNumberColumn)
        {
            columnNamesToInsert.Add(Constants.AutoGeneratedIndexNumberColumn);
        }

        var sql = $"COPY {tableName} ({string.Join(',', columnNamesToInsert.Select(x => $"\"{GetDbColumnName(x, columnNameMappings)}\""))}) FROM STDIN (FORMAT binary)";

        using var writer = connectionContext.Connection.BeginBinaryImport(sql);

        long idx = 0;

        foreach (T item in data)
        {
            writer.StartRow();

            foreach (var name in columnNamesToInsert)
            {
                var prop = updatablePros.FirstOrDefault(x => x.Name == name);

                if (prop == null)
                {
                    continue;
                }

                var value = GetProviderValue(prop, item, valueConverters);

                writer.Write(value);
            }

            if (addIndexNumberColumn)
            {
                writer.Write(idx);
            }

            idx++;
        }

        writer.Complete();
    }

    public static async Task SqlBulkCopyAsync<T>(this IEnumerable<T> data, string tableName, IEnumerable<string> propertyNames, IReadOnlyDictionary<string, string> columnNameMappings, bool addIndexNumberColumn, ConnectionContext connectionContext, BulkOptions options = null, IReadOnlyDictionary<string, ValueConverter> valueConverters = null, CancellationToken cancellationToken = default)
    {
        options ??= DefaultBulkOptions;

        var properties = TypeDescriptor.GetProperties(typeof(T));

        var updatablePros = new List<PropertyDescriptor>();
        foreach (PropertyDescriptor prop in properties)
        {
            if (propertyNames.Contains(prop.Name))
            {
                updatablePros.Add(prop);
            }
        }

        var columnNamesToInsert = propertyNames.ToList();

        if (addIndexNumberColumn)
        {
            columnNamesToInsert.Add(Constants.AutoGeneratedIndexNumberColumn);
        }

        var sql = $"COPY {tableName} ({string.Join(',', columnNamesToInsert.Select(x => $"\"{GetDbColumnName(x, columnNameMappings)}\""))}) FROM STDIN (FORMAT binary)";

        using var writer = await connectionContext.Connection.BeginBinaryImportAsync(sql, cancellationToken);

        long idx = 0;

        foreach (T item in data)
        {
            cancellationToken.ThrowIfCancellationRequested();

            await writer.StartRowAsync(cancellationToken);

            foreach (var name in columnNamesToInsert)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var prop = updatablePros.FirstOrDefault(x => x.Name == name);

                if (prop == null)
                {
                    continue;
                }

                var value = GetProviderValue(prop, item, valueConverters);

                await writer.WriteAsync(value, cancellationToken);
            }

            if (addIndexNumberColumn)
            {
                await writer.WriteAsync(idx, cancellationToken);
            }

            idx++;
        }

        await writer.CompleteAsync(cancellationToken);
    }

    private static string GetDbColumnName(string columName, IReadOnlyDictionary<string, string> columnNameMappings)
    {
        if (columnNameMappings == null)
        {
            return columName;
        }

        return columnNameMappings.TryGetValue(columName, out string value) ? value : columName;
    }

    private static object GetProviderValue<T>(PropertyDescriptor property, T item, IReadOnlyDictionary<string, ValueConverter> valueConverters)
    {
        if (valueConverters != null && valueConverters.TryGetValue(property.Name, out var converter))
        {
            return converter.ConvertToProvider(property.GetValue(item));
        }

        var type = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;
        var tempValue = property.GetValue(item);
        var value = type.IsEnum && tempValue != null ? (int)tempValue : tempValue;

        return value;
    }
}
