using EntityFrameworkCore.PostgreSQL.SimpleBulks.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace EntityFrameworkCore.PostgreSQL.SimpleBulks.BulkMerge;

public class BulkMergeBuilder<T>
{
    private TableInfor<T> _table;
    private IReadOnlyCollection<string> _idColumns;
    private IReadOnlyCollection<string> _updateColumnNames;
    private IReadOnlyCollection<string> _insertColumnNames;
    private string _outputIdColumn;
    private BulkMergeOptions _options = BulkMergeOptions.DefaultOptions;
    private readonly ConnectionContext _connectionContext;

    public BulkMergeBuilder(ConnectionContext connectionContext)
    {
        _connectionContext = connectionContext;
    }

    public BulkMergeBuilder<T> ToTable(TableInfor<T> table)
    {
        _table = table;

        _outputIdColumn = table?.OutputId?.Name;

        return this;
    }

    public BulkMergeBuilder<T> WithId(IReadOnlyCollection<string> idColumns)
    {
        _idColumns = idColumns;
        return this;
    }

    public BulkMergeBuilder<T> WithId(Expression<Func<T, object>> idSelector)
    {
        var idColumn = idSelector.Body.GetMemberName();
        _idColumns = string.IsNullOrEmpty(idColumn) ? idSelector.Body.GetMemberNames() : [idColumn];
        return this;
    }

    public BulkMergeBuilder<T> WithUpdateColumns(IReadOnlyCollection<string> updateColumnNames)
    {
        _updateColumnNames = updateColumnNames;
        return this;
    }

    public BulkMergeBuilder<T> WithUpdateColumns(Expression<Func<T, object>> updateColumnNamesSelector)
    {
        _updateColumnNames = updateColumnNamesSelector.Body.GetMemberNames().ToArray();
        return this;
    }

    public BulkMergeBuilder<T> WithInsertColumns(IReadOnlyCollection<string> insertColumnNames)
    {
        _insertColumnNames = insertColumnNames;
        return this;
    }

    public BulkMergeBuilder<T> WithInsertColumns(Expression<Func<T, object>> insertColumnNamesSelector)
    {
        _insertColumnNames = insertColumnNamesSelector.Body.GetMemberNames().ToArray();
        return this;
    }

    public BulkMergeBuilder<T> WithBulkOptions(BulkMergeOptions options)
    {
        _options = options ?? BulkMergeOptions.DefaultOptions;
        return this;
    }

    public BulkMergeResult Execute(IReadOnlyCollection<T> data)
    {
        if (data.Count() == 1)
        {
            return SingleMerge(data.First());
        }

        if (!_updateColumnNames.Any() && !_insertColumnNames.Any())
        {
            return new BulkMergeResult();
        }

        bool returnDbGeneratedId = _options.ReturnDbGeneratedId && !string.IsNullOrEmpty(_outputIdColumn) && _insertColumnNames.Any();

        var temptableName = $"\"{Guid.NewGuid()}\"";

        var propertyNames = _updateColumnNames.Select(RemoveOperator).ToList();
        propertyNames.AddRange(_idColumns);
        propertyNames.AddRange(_insertColumnNames);
        propertyNames = propertyNames.Distinct().ToList();

        var sqlCreateTemptable = typeof(T).GenerateTempTableDefinition(temptableName, propertyNames, null, _table.ColumnTypeMappings, addIndexNumberColumn: returnDbGeneratedId);

        var mergeStatementBuilder = new StringBuilder();

        var joinCondition = string.Join(" and ", _idColumns.Select(x =>
           {
               string collation = !string.IsNullOrEmpty(_options.Collation) && _table.GetProviderClrType(x) == typeof(string) ?
            $" COLLATE \"{_options.Collation}\"" : string.Empty;
               return $"s.\"{x}\"{collation} = t.\"{_table.GetDbColumnName(x)}\"{collation}";
           }));

        mergeStatementBuilder.AppendLine($"MERGE INTO {_table.SchemaQualifiedTableName} AS t");
        mergeStatementBuilder.AppendLine($"    USING {temptableName} AS s");
        mergeStatementBuilder.AppendLine($"ON ({joinCondition})");

        if (_updateColumnNames.Any())
        {
            mergeStatementBuilder.AppendLine($"WHEN MATCHED");
            mergeStatementBuilder.AppendLine($"    THEN UPDATE SET");
            mergeStatementBuilder.AppendLine(string.Join("," + Environment.NewLine, _updateColumnNames.Select(x => "         " + CreateSetStatement(x, "s"))));
        }

        if (_insertColumnNames.Any())
        {
            mergeStatementBuilder.AppendLine($"WHEN NOT MATCHED");
            mergeStatementBuilder.AppendLine($"    THEN INSERT ({string.Join(", ", _insertColumnNames.Select(x => $"\"{_table.GetDbColumnName(x)}\""))})");
            mergeStatementBuilder.AppendLine($"         VALUES ({string.Join(", ", _insertColumnNames.Select(x => $"s.\"{x}\""))})");
        }

        if (returnDbGeneratedId)
        {
            mergeStatementBuilder.AppendLine($"RETURNING merge_action() as MERGE_ACTION, t.\"{_table.GetDbColumnName(_outputIdColumn)}\", s.\"{Constants.AutoGeneratedIndexNumberColumn}\"");
        }
        else
        {
            mergeStatementBuilder.AppendLine($"RETURNING merge_action() as MERGE_ACTION");
        }

        mergeStatementBuilder.AppendLine(";");

        _connectionContext.EnsureOpen();

        Log($"Begin creating temp table:{Environment.NewLine}{sqlCreateTemptable}");
        using (var createTemptableCommand = _connectionContext.CreateTextCommand(sqlCreateTemptable, _options))
        {
            createTemptableCommand.ExecuteNonQuery();
        }
        Log("End creating temp table.");

        Log($"Begin executing SqlBulkCopy. TableName: {temptableName}");
        _connectionContext.SqlBulkCopy(data, temptableName, propertyNames, null, returnDbGeneratedId, _options, valueConverters: _table.ValueConverters);
        Log("End executing SqlBulkCopy.");

        var sqlMergeStatement = mergeStatementBuilder.ToString();

        Log($"Begin merging temp table:{Environment.NewLine}{sqlMergeStatement}");

        BulkMergeResult result = new();
        Dictionary<long, object> returnedIds = null;
        string outputIdDbColumnName = null;

        if (returnDbGeneratedId)
        {
            returnedIds = new Dictionary<long, object>();
            outputIdDbColumnName = _table.GetDbColumnName(_outputIdColumn);
        }

        using (var updateCommand = _connectionContext.CreateTextCommand(sqlMergeStatement, _options))
        {
            using var reader = updateCommand.ExecuteReader();

            while (reader.Read())
            {
                var action = reader["MERGE_ACTION"] as string;

                if (action == "INSERT")
                {
                    if (returnDbGeneratedId)
                    {
                        returnedIds[(reader[Constants.AutoGeneratedIndexNumberColumn] as long?).Value] = reader[outputIdDbColumnName];
                    }

                    result.InsertedRows++;
                }
                else if (action == "UPDATE")
                {
                    result.UpdatedRows++;
                }

                result.AffectedRows++;
            }
        }

        Log("End merging temp table.");

        if (returnDbGeneratedId)
        {
            var idProperty = PropertiesCache<T>.GetProperty(_outputIdColumn);

            long idx = 0;
            foreach (var row in data)
            {
                if (returnedIds.TryGetValue(idx, out object id))
                {
                    idProperty.SetValue(row, id);
                }

                idx++;
            }
        }

        return result;
    }

    private string CreateSetStatement(string prop, string rightTable)
    {
        string sqlOperator = "=";
        string sqlProp = RemoveOperator(prop);

        if (prop.EndsWith("+="))
        {
            sqlOperator = "+=";
        }

        return $"\"{_table.GetDbColumnName(sqlProp)}\" {sqlOperator} {rightTable}.\"{sqlProp}\"";
    }

    private static string RemoveOperator(string prop)
    {
        var rs = prop.Replace("+=", "");
        return rs;
    }

    private void Log(string message)
    {
        _options?.LogTo?.Invoke($"{DateTimeOffset.Now:yyyy-MM-dd HH:mm:ss.fff zzz} [BulkMerge]: {message}");
    }

    private void LogParameters(List<ParameterInfo> parameters)
    {
        if (_options?.LogTo == null)
        {
            return;
        }

        foreach (var parameter in parameters)
        {
            _options.LogTo?.Invoke($"{DateTimeOffset.Now:yyyy-MM-dd HH:mm:ss.fff zzz} [BulkMerge][Parameter]: {parameter}");
        }
    }

    public async Task<BulkMergeResult> ExecuteAsync(IReadOnlyCollection<T> data, CancellationToken cancellationToken = default)
    {
        if (data.Count() == 1)
        {
            return await SingleMergeAsync(data.First(), cancellationToken);
        }

        if (!_updateColumnNames.Any() && !_insertColumnNames.Any())
        {
            return new BulkMergeResult();
        }

        bool returnDbGeneratedId = _options.ReturnDbGeneratedId && !string.IsNullOrEmpty(_outputIdColumn) && _insertColumnNames.Any();

        var temptableName = $"\"{Guid.NewGuid()}\"";

        var propertyNames = _updateColumnNames.Select(RemoveOperator).ToList();
        propertyNames.AddRange(_idColumns);
        propertyNames.AddRange(_insertColumnNames);
        propertyNames = propertyNames.Distinct().ToList();

        var sqlCreateTemptable = typeof(T).GenerateTempTableDefinition(temptableName, propertyNames, null, _table.ColumnTypeMappings, addIndexNumberColumn: returnDbGeneratedId);

        var mergeStatementBuilder = new StringBuilder();

        var joinCondition = string.Join(" and ", _idColumns.Select(x =>
        {
            string collation = !string.IsNullOrEmpty(_options.Collation) && _table.GetProviderClrType(x) == typeof(string) ?
$" COLLATE \"{_options.Collation}\"" : string.Empty;
            return $"s.\"{x}\"{collation} = t.\"{_table.GetDbColumnName(x)}\"{collation}";
        }));

        mergeStatementBuilder.AppendLine($"MERGE INTO {_table.SchemaQualifiedTableName} AS t");
        mergeStatementBuilder.AppendLine($"    USING {temptableName} AS s");
        mergeStatementBuilder.AppendLine($"ON ({joinCondition})");

        if (_updateColumnNames.Any())
        {
            mergeStatementBuilder.AppendLine($"WHEN MATCHED");
            mergeStatementBuilder.AppendLine($"    THEN UPDATE SET");
            mergeStatementBuilder.AppendLine(string.Join("," + Environment.NewLine, _updateColumnNames.Select(x => "         " + CreateSetStatement(x, "s"))));
        }

        if (_insertColumnNames.Any())
        {
            mergeStatementBuilder.AppendLine($"WHEN NOT MATCHED");
            mergeStatementBuilder.AppendLine($"    THEN INSERT ({string.Join(", ", _insertColumnNames.Select(x => $"\"{_table.GetDbColumnName(x)}\""))})");
            mergeStatementBuilder.AppendLine($"         VALUES ({string.Join(", ", _insertColumnNames.Select(x => $"s.\"{x}\""))})");
        }

        if (returnDbGeneratedId)
        {
            mergeStatementBuilder.AppendLine($"RETURNING merge_action() as MERGE_ACTION, t.\"{_table.GetDbColumnName(_outputIdColumn)}\", s.\"{Constants.AutoGeneratedIndexNumberColumn}\"");
        }
        else
        {
            mergeStatementBuilder.AppendLine($"RETURNING merge_action() as MERGE_ACTION");
        }

        mergeStatementBuilder.AppendLine(";");

        await _connectionContext.EnsureOpenAsync(cancellationToken);

        Log($"Begin creating temp table:{Environment.NewLine}{sqlCreateTemptable}");
        using (var createTemptableCommand = _connectionContext.CreateTextCommand(sqlCreateTemptable, _options))
        {
            await createTemptableCommand.ExecuteNonQueryAsync(cancellationToken);
        }
        Log("End creating temp table.");

        Log($"Begin executing SqlBulkCopy. TableName: {temptableName}");
        await _connectionContext.SqlBulkCopyAsync(data, temptableName, propertyNames, null, returnDbGeneratedId, _options, valueConverters: _table.ValueConverters, cancellationToken: cancellationToken);
        Log("End executing SqlBulkCopy.");

        var sqlMergeStatement = mergeStatementBuilder.ToString();

        Log($"Begin merging temp table:{Environment.NewLine}{sqlMergeStatement}");

        BulkMergeResult result = new();
        Dictionary<long, object> returnedIds = null;
        string outputIdDbColumnName = null;

        if (returnDbGeneratedId)
        {
            returnedIds = new Dictionary<long, object>();
            outputIdDbColumnName = _table.GetDbColumnName(_outputIdColumn);
        }

        using (var updateCommand = _connectionContext.CreateTextCommand(sqlMergeStatement, _options))
        {
            using var reader = await updateCommand.ExecuteReaderAsync(cancellationToken);

            while (await reader.ReadAsync(cancellationToken))
            {
                var action = reader["MERGE_ACTION"] as string;

                if (action == "INSERT")
                {
                    if (returnDbGeneratedId)
                    {
                        returnedIds[(reader[Constants.AutoGeneratedIndexNumberColumn] as long?).Value] = reader[outputIdDbColumnName];
                    }

                    result.InsertedRows++;
                }
                else if (action == "UPDATE")
                {
                    result.UpdatedRows++;
                }

                result.AffectedRows++;
            }
        }

        Log("End merging temp table.");

        if (returnDbGeneratedId)
        {
            var idProperty = PropertiesCache<T>.GetProperty(_outputIdColumn);

            long idx = 0;
            foreach (var row in data)
            {
                if (returnedIds.TryGetValue(idx, out object id))
                {
                    idProperty.SetValue(row, id);
                }

                idx++;
            }
        }

        return result;
    }

    public BulkMergeResult SingleMerge(T data)
    {
        if (!_updateColumnNames.Any() && !_insertColumnNames.Any())
        {
            return new BulkMergeResult();
        }

        bool returnDbGeneratedId = _options.ReturnDbGeneratedId && !string.IsNullOrEmpty(_outputIdColumn) && _insertColumnNames.Any();

        var propertyNames = _updateColumnNames.Select(RemoveOperator).ToList();
        propertyNames.AddRange(_idColumns);
        propertyNames.AddRange(_insertColumnNames);
        propertyNames = propertyNames.Distinct().ToList();

        var mergeStatementBuilder = new StringBuilder();

        var joinCondition = string.Join(" and ", _idColumns.Select(x =>
       {
           string collation = !string.IsNullOrEmpty(_options.Collation) && _table.GetProviderClrType(x) == typeof(string) ?
            $" COLLATE \"{_options.Collation}\"" : string.Empty;
           return $"s.\"{x}\"{collation} = t.\"{_table.GetDbColumnName(x)}\"{collation}";
       }));

        var parameterNames = string.Join(", ", propertyNames.Select(x => "@" + x));
        var columnNames = string.Join(", ", propertyNames.Select(x => "\"" + x + "\""));

        mergeStatementBuilder.AppendLine($"MERGE INTO {_table.SchemaQualifiedTableName} AS t");
        mergeStatementBuilder.AppendLine($"    USING (values ({parameterNames})) AS s ({columnNames}) ");
        mergeStatementBuilder.AppendLine($"ON ({joinCondition})");

        if (_updateColumnNames.Any())
        {
            mergeStatementBuilder.AppendLine($"WHEN MATCHED");
            mergeStatementBuilder.AppendLine($"    THEN UPDATE SET");
            mergeStatementBuilder.AppendLine(string.Join("," + Environment.NewLine, _updateColumnNames.Select(x => "         " + CreateSetStatement(x, "s"))));
        }

        if (_insertColumnNames.Any())
        {
            mergeStatementBuilder.AppendLine($"WHEN NOT MATCHED");
            mergeStatementBuilder.AppendLine($"    THEN INSERT ({string.Join(", ", _insertColumnNames.Select(x => $"\"{_table.GetDbColumnName(x)}\""))})");
            mergeStatementBuilder.AppendLine($"         VALUES ({string.Join(", ", _insertColumnNames.Select(x => $"s.\"{x}\""))})");
        }

        if (returnDbGeneratedId)
        {
            mergeStatementBuilder.AppendLine($"RETURNING merge_action() as MERGE_ACTION, t.\"{_table.GetDbColumnName(_outputIdColumn)}\"");
        }
        else
        {
            mergeStatementBuilder.AppendLine($"RETURNING merge_action() as MERGE_ACTION");
        }

        mergeStatementBuilder.AppendLine(";");

        _connectionContext.EnsureOpen();

        var sqlMergeStatement = mergeStatementBuilder.ToString();

        Log($"Begin merging temp table:{Environment.NewLine}{sqlMergeStatement}");

        BulkMergeResult result = new();
        string outputIdDbColumnName = null;

        if (returnDbGeneratedId)
        {
            outputIdDbColumnName = _table.GetDbColumnName(_outputIdColumn);
        }

        using (var updateCommand = _connectionContext.CreateTextCommand(sqlMergeStatement, _options))
        {
            LogParameters(_table.CreateNpgsqlParameters(updateCommand, data, propertyNames, autoAdd: true));

            using var reader = updateCommand.ExecuteReader();

            while (reader.Read())
            {
                var action = reader["MERGE_ACTION"] as string;

                if (action == "INSERT")
                {
                    if (returnDbGeneratedId)
                    {
                        var idProperty = PropertiesCache<T>.GetProperty(_outputIdColumn);
                        idProperty.SetValue(data, reader[outputIdDbColumnName]);
                    }

                    result.InsertedRows++;
                }
                else if (action == "UPDATE")
                {
                    result.UpdatedRows++;
                }

                result.AffectedRows++;
            }
        }

        Log("End merging temp table.");

        return result;
    }

    public async Task<BulkMergeResult> SingleMergeAsync(T data, CancellationToken cancellationToken = default)
    {
        if (!_updateColumnNames.Any() && !_insertColumnNames.Any())
        {
            return new BulkMergeResult();
        }

        bool returnDbGeneratedId = _options.ReturnDbGeneratedId && !string.IsNullOrEmpty(_outputIdColumn) && _insertColumnNames.Any();

        var propertyNames = _updateColumnNames.Select(RemoveOperator).ToList();
        propertyNames.AddRange(_idColumns);
        propertyNames.AddRange(_insertColumnNames);
        propertyNames = propertyNames.Distinct().ToList();

        var mergeStatementBuilder = new StringBuilder();

        var joinCondition = string.Join(" and ", _idColumns.Select(x =>
              {
                  string collation = !string.IsNullOrEmpty(_options.Collation) && _table.GetProviderClrType(x) == typeof(string) ?
   $" COLLATE \"{_options.Collation}\"" : string.Empty;
                  return $"s.\"{x}\"{collation} = t.\"{_table.GetDbColumnName(x)}\"{collation}";
              }));

        var parameterNames = string.Join(", ", propertyNames.Select(x => "@" + x));
        var columnNames = string.Join(", ", propertyNames.Select(x => "\"" + x + "\""));

        mergeStatementBuilder.AppendLine($"MERGE INTO {_table.SchemaQualifiedTableName} AS t");
        mergeStatementBuilder.AppendLine($"    USING (values ({parameterNames})) AS s ({columnNames}) ");
        mergeStatementBuilder.AppendLine($"ON ({joinCondition})");

        if (_updateColumnNames.Any())
        {
            mergeStatementBuilder.AppendLine($"WHEN MATCHED");
            mergeStatementBuilder.AppendLine($"    THEN UPDATE SET");
            mergeStatementBuilder.AppendLine(string.Join("," + Environment.NewLine, _updateColumnNames.Select(x => "         " + CreateSetStatement(x, "s"))));
        }

        if (_insertColumnNames.Any())
        {
            mergeStatementBuilder.AppendLine($"WHEN NOT MATCHED");
            mergeStatementBuilder.AppendLine($"    THEN INSERT ({string.Join(", ", _insertColumnNames.Select(x => $"\"{_table.GetDbColumnName(x)}\""))})");
            mergeStatementBuilder.AppendLine($"         VALUES ({string.Join(", ", _insertColumnNames.Select(x => $"s.\"{x}\""))})");
        }

        if (returnDbGeneratedId)
        {
            mergeStatementBuilder.AppendLine($"RETURNING merge_action() as MERGE_ACTION, t.\"{_table.GetDbColumnName(_outputIdColumn)}\"");
        }
        else
        {
            mergeStatementBuilder.AppendLine($"RETURNING merge_action() as MERGE_ACTION");
        }

        mergeStatementBuilder.AppendLine(";");

        await _connectionContext.EnsureOpenAsync(cancellationToken);

        var sqlMergeStatement = mergeStatementBuilder.ToString();

        Log($"Begin merging temp table:{Environment.NewLine}{sqlMergeStatement}");

        BulkMergeResult result = new();
        string outputIdDbColumnName = null;

        if (returnDbGeneratedId)
        {
            outputIdDbColumnName = _table.GetDbColumnName(_outputIdColumn);
        }

        using (var updateCommand = _connectionContext.CreateTextCommand(sqlMergeStatement, _options))
        {
            LogParameters(_table.CreateNpgsqlParameters(updateCommand, data, propertyNames, autoAdd: true));

            using var reader = await updateCommand.ExecuteReaderAsync(cancellationToken);

            while (await reader.ReadAsync(cancellationToken))
            {
                var action = reader["MERGE_ACTION"] as string;

                if (action == "INSERT")
                {
                    if (returnDbGeneratedId)
                    {
                        var idProperty = PropertiesCache<T>.GetProperty(_outputIdColumn);
                        idProperty.SetValue(data, reader[outputIdDbColumnName]);
                    }

                    result.InsertedRows++;
                }
                else if (action == "UPDATE")
                {
                    result.UpdatedRows++;
                }

                result.AffectedRows++;
            }
        }

        Log("End merging temp table.");

        return result;
    }
}
